pipeline {
     agent any
     environment {
        RunTests = "False"
        TestsRunSuccessfully = "True"
    }
     stages {
         stage('Initialize the variables') {
             // Each stage is made up of steps
             steps{
                 script{
                     PROCESS_OUTPUT_PATH = "${WORKSPACE}\\Process\\Output\\${BUILD_NUMBER}"
                     TEST_OUTPUT_PATH = "${WORKSPACE}\\Test\\Output\\${BUILD_NUMBER}"
                     ASSETS_FILE_PATH = "${WORKSPACE}\\assets.csv"
                 }
             }               
         }
         stage('Checkout code') {
             steps {
                 // Get some code from a GitHub repository
                 git branch: 'main',
                 credentialsId: '8256c430-4681-428d-9199-359ec61b5327',
                 url: 'https://github.com/SebastianBalan/JenkinsPipeline'
             }
         }
         stage('Run Workflow Analyzer') {
             steps {
                 echo 'Workflow Analyzer'
                 powershell '''param(
                        $ProjectFilePath="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\PipelineGateEmail\\project.json",
                        $ExecutableFilePath="C:\\Users\\sebastian.balan\\AppData\\Local\\Programs\\UiPath\\Studio\\UiPath.Studio.CommandLine.exe",
                        $OutputFilePath="$(Get-Date -Format \'yyyy-MM-dd-HH-mm-ss\')-Workflow-Analysis.json",
                    )
                
                
                    Write-Output "$(Get-Date -Format 'HH:mm:ss') - STARTED - Static Code Analyzer"

                    $Command = "$ExecutableFilePath analyze -p `'$ProjectFilePath`'"
                    Invoke-Expression $Command | Out-File -FilePath $OutputFilePath
                    $rp = Get-Content $OutputFilePath | foreach {$_.replace("#json","")}
                    
                    Set-Content -Path $OutputFilePath -Value $rp
                    #Write-Output $rp
                    $JO = Get-Content $OutputFilePath | ConvertFrom-Json
                    
                    #Write-Output $JO.'056582b5-7ca5-414a-a7fd-2effa9d41931-ErrorSeverity'
                    $totalErros=0
                    
                    
                    $ErrorCode = "Error Code"
                    $ErrorSeverity = "Error Severity"
                    $Description = "Description"
                    $Recommendation = "Recommendation"
                    $FilePath = "File Path"
                    
                    $row=2
                    foreach ($ky in $JO.PSObject.Properties)
                    {
                    	if ($ky.Name.EndsWith("ErrorCode"))
                    	{
                    		$ErrorCode = $ky.Value
                    	}
                    	if ($ky.Name.EndsWith("Description"))
                    	{
                    		$Description = $ky.Value
                    	}
                    	if ($ky.Name.EndsWith("FilePath"))
                    	{
                    		$FilePath = $ky.Value
                    	}
                    	if ($ky.Name.EndsWith("Recommendation"))
                    	{
                    		$Recommendation = $ky.Value
                    		if ($ErrorSeverity = "Error")
                    		{ 
                    			Write-Output "Error code: $ErrorCode, File: $FilePath, $Description"
                    		}
                    		$row++
                    	}
                    
                    	if ($ky.Name.EndsWith("ErrorSeverity"))
                    	{
                    		$ErrorSeverity = $ky.Value
                    		if ($ky.Value.Equals("Error"))
                    		{
                    			$totalErros++
                    		}
                    	}
                    
                    }
                    
                    
                    
                    #Write-Output to pipeline
                    
                    Write-Output "$(Get-Date -Format 'HH:mm:ss') - COMPLETED - Static Code Analyzer"
                    
                    #Get-Content $OutputFilePath | ConvertFrom-Json | ConvertTo-Csv | Out-File $CSVFilePath
                    
                    
                    Write-Output "Total Number of Violations = $totalErros"
                    if ($totalErros > 0)
                    {
                    	Exit 1
                    }'''
             }
         }
         stage('Deploy assets') {
             when {
                equals expected : 'True', actual: TestsRunSuccessfully
            }
             steps {
                 echo 'UiPathDeployAssets'
                 UiPathAssets (
                     assetsAction: DeployAssets(),
                     credentials: Token(accountName: 'aitraining', credentialsId: 'userkeyOrch'),
                     filePath: ASSETS_FILE_PATH,
                     folderName: 'sebi',
                     orchestratorAddress: 'https://cloud.uipath.com/aitraining',
                     orchestratorTenant: 'UiPathDefault',
                     traceLevel: 'None'
                )
             }
         } 
         stage('Build code for Process') {
             steps {
                 echo 'UiPathPack'
                 echo PROCESS_OUTPUT_PATH
                 UiPathPack (
                     outputPath: PROCESS_OUTPUT_PATH,
                     outputType: 'Process',
                     projectJsonPath: "${WORKSPACE}",
                     runWorkflowAnalysis: false,
                     traceLevel: 'None',
                     version: AutoVersion()
                 )
             }
         }
         stage('Test code') {
            when {
                equals expected : 'True', actual: RunTests
            }
             steps {
                 echo 'UiPathTest'
                 UiPathTest(
                     credentials: Token(accountName: 'aitraining', credentialsId: 'userkeyOrch'),
                     folderName: 'sebi',
                     orchestratorAddress: 'https://cloud.uipath.com/aitraining',
                     orchestratorTenant: 'UiPathDefault',
                     parametersFilePath: '',
                     testResultsOutputPath: '',
                     testTarget: TestSet('JenkinsTestPipeline'),
                     timeout: 500,
                     traceLevel: 'Verbose'
                 )
                 script {
                     if (currentBuild.result == 'UNSTABLE'){
                         currentBuild.result = 'FAILURE'
                         TestsRunSuccessfully = 'False'
                     }
                 }
             }
         }
         stage('Deploy code') {
             when {
                equals expected : 'True', actual: TestsRunSuccessfully
            }
             steps {
                 echo 'UiPathDeploy'
                 UiPathDeploy (
                    createProcess: true,
                    credentials: Token(accountName: 'aitraining', credentialsId: 'userkeyOrch'),
                    entryPointPaths: 'Main.xaml',
                    environments: '',
                    folderName: 'sebi',
                    orchestratorAddress: 'https://cloud.uipath.com/aitraining',
                    orchestratorTenant: 'UiPathDefault',
                    packagePath: PROCESS_OUTPUT_PATH,
                    traceLevel: 'Verbose'
                )
             }
         }   
     }
 }